// src/app/components/about/about.component.ts
import { Component } from '@angular/core';
import { RouterLink } from '@angular/router';

@Component({
  selector: 'app-about',
  standalone: true,
  imports: [RouterLink],
  template: `
    <section class="py-32 px-6 bg-muted/30">
      <div class="max-w-4xl mx-auto">
        <h2 class="text-5xl md:text-6xl font-bold mb-12 text-center animate-in fade-in slide-in-from-left-4 duration-1000">
          About Me
        </h2>
        
        <div class="text-lg md:text-xl text-muted-foreground leading-relaxed text-center">
          <p class="animate-in fade-in slide-in-from-left-4 duration-1000">
            With a strong background in backend and frontend development, I specialize in delivering secure and high-performance systems that support large-scale operations. Over the past eight years, I've collaborated with banks, brokerages, and cross-functional teams to accelerate delivery and elevate software quality. Today, my focus is on crafting meaningful digital experiences while continuously learning and pushing the boundaries of what technology can do. Currently, I work as a Software Engineer at <a routerLink="/projects" [queryParams]="{project: 'sporting-cp'}" class="text-foreground font-medium hover:text-accent transition-colors underline underline-offset-4">Sporting Clube de Portugal</a>, where I build and maintain systems that serve thousands of users daily.
          </p>
          <p class="animate-in fade-in slide-in-from-left-4 duration-1000">
            When I'm off the keyboard, you'll find me behind a camera, discovering new music, or developing entrepreneurial projects.
          </p>
        </div>
      </div>
    </section>
  `,
  styles: []
})
export class AboutComponent {
}

// src/components/About.tsx
export const About = () => {
  return (
    <section className="py-32 px-6 bg-muted/30">
      <div className="max-w-4xl mx-auto">
        <h2 className="text-5xl md:text-6xl font-bold mb-12 animate-in fade-in slide-in-from-left-4 duration-1000">
          About Me
        </h2>
        
        <div className="space-y-6 text-lg md:text-xl text-muted-foreground leading-relaxed">
          <p className="animate-in fade-in slide-in-from-left-4 duration-1000 delay-100">
            I'm a passionate software engineer with a love for creating elegant, efficient solutions 
            to complex problems. My journey in tech is driven by curiosity and a commitment to 
            continuous learning.
          </p>
          
          <p className="animate-in fade-in slide-in-from-left-4 duration-1000 delay-200">
            Currently, I work as a Full-Stack Developer at <span className="text-foreground font-medium">Sporting Clube de Portugal</span>, 
            where I build and maintain systems that serve thousands of users daily.
          </p>
          
          <p className="animate-in fade-in slide-in-from-left-4 duration-1000 delay-300">
            When I'm not coding, you'll find me exploring photography, enjoying music, 
            or diving into entrepreneurship ventures. I believe in the power of technology 
            to transform ideas into reality.
          </p>
        </div>
      </div>
    </section>
  );
};
